version: '3.1'

# base service definitions, environment variables secrets should be updated and loaded from docker-compose.secrets.yml

services:
  db:
    image: postgres:9.6.8-alpine
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: podcast_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
  cache:
    restart: always
    image: redis:5.0.4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    expose:
      - "6379"

volumes:
  postgres_data:
  redis_data:
